#ifndef TIPOS_H
#define TIPOS_H

typedef enum {ST_OK, ST_ERROR_PUNTERO_NULO, ST_ERROR_NOMEM, ST_ERROR_CANT_ARGC, ST_ERROR_OPEN_ARCHIVO, ST_ERROR_DESTRUIR_ARREGLO, ST_ERROR_CREAR_LISTA, ST_ERROR_DESTRUIR_VECTOR, ST_ERROR_DESTRUIR_LISTA, ST_ERROR_CREAR_VECTOR, ST_ERROR_IMPRIMIR_DATOS} status_t;

#define MAX_LENGTH 50
#define MAX_LENGTH_MENSAJE_LARGO 166
#define CROCHETE_1 '['
#define CROCHETE_2 ']'
#define IGUAL '='
#define COMA ','

#endif
